services:
  nginx:
    image: nginx:1.27-alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./build:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  php:
    container_name: php
    build:
      context: ./php
    volumes:
      - ./build:/var/www/html
    environment:
      - MYSQL_DATABASE=$(MYSQL_DATABASE)
      - MYSQL_USER=$(MYSQL_USER)
      - MYSQL_PASSWORD=$(MYSQL_PASSWORD)
    depends_on:
      - mysql

  mysql:
    container_name: mysql
    build:
      context: ./mysql
    environment:
      - MYSQL_ROOT_PASSWORD=$(MYSQL_ROOT_PASSWORD)
      - MYSQL_DATABASE=$(MYSQL_DATABASE)
      - MYSQL_USER=$(MYSQL_USER)
      - MYSQL_PASSWORD=$(MYSQL_PASSWORD)
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
